# service configs
port: 52520
max_num_of_nodes: 16
request_timeout: 2

# neighbour configs
finger_table_enabled: false
neighbour_check: false
predecessor: "compute-1-1"
predecessor_port: ""
successor: "compute-1-1"
successor_port: ""

# logger configs
colors_enabled: true
log_level: "TRACE"
file_path: true
