# service configs
port: 52520
request_timeout_sec: 8
ttl_min: 180

# neighbour configs
probe_interval_sec: 10
detect_crash_interval_sec: 5

# logger configs
colors_enabled: true
log_level: "TRACE"
file_path: true
