# service configs
port: 52520
request_timeout_sec: 5
ttl_min: 180

# neighbour configs
probe_interval_sec: 10
detect_crash_timeout_sec: 2

# logger configs
colors_enabled: true
log_level: "TRACE"
file_path: true
